Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import openpifpaf.logs
openpifpaf.logs.Plots(['cifar10_tutorial.pkl.log']).show_all()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mException[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-6-db0dd136ad46>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mopenpifpaf[0m[0;34m.[0m[0mlogs[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mopenpifpaf[0m[0;34m.[0m[0mlogs[0m[0;34m.[0m[0mPlots[0m[0;34m([0m[0;34m[[0m[0;34m'cifar10_tutorial.pkl.log'[0m[0;34m][0m[0;34m)[0m[0;34m.[0m[0mshow_all[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/openpifpaf/logs.py[0m in [0;36mshow_all[0;34m(self, show_mtl_sigmas)[0m
[1;32m    315[0m [0;34m[0m[0m
[1;32m    316[0m     [0;32mdef[0m [0mshow_all[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mshow_mtl_sigmas[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 317[0;31m         [0mpprint[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mprocess_arguments[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    318[0m [0;34m[0m[0m
[1;32m    319[0m         [0mall_field_names[0m [0;34m=[0m [0;34m[[0m[0mf[0m [0;32mfor[0m [0mfs[0m [0;32min[0m [0mself[0m[0;34m.[0m[0mfield_names[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mvalues[0m[0;34m([0m[0;34m)[0m [0;32mfor[0m [0mf[0m [0;32min[0m [0mfs[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/openpifpaf/logs.py[0m in [0;36mprocess_arguments[0;34m(self)[0m
[1;32m     88[0m     [0;32mdef[0m [0mprocess_arguments[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     89[0m         [0;32mif[0m [0;32mnot[0m [0mself[0m[0;34m.[0m[0mdatas[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 90[0;31m             [0;32mraise[0m [0mException[0m[0;34m([0m[0;34m'no data'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     91[0m         return {label: data['process'][0]['argv'][1:]
[1;32m     92[0m                 for data, label in zip(self.datas, self.labels)}

[0;31mException[0m: no data
Exception: no data

